const data = [
  {
    id: 1,
    name: "MS Dhoni",
    position: "Batting & keeping",
    team: "Csk",
    img: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1.png",
  },
  {
    id: 2,
    name: "Ambati Rayudu",
    position: "Batting",
    team: "Csk",
    img: "https://assets.iplt20.com/ipl/IPLHeadshot2022/100.png",
  },
  {
    id: 3,
    name: "Ravindra jadeja",
    position: "All Rounder",
    team: "Csk",
    img: "https://assets.iplt20.com/ipl/IPLHeadshot2022/9.png",
  },
  {
    id: 4,
    name: "Moeen Ali",
    position: "All Rounder",
    team: "Csk",
    img: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1735.png",
  },
  {
    id: 5,
    name: "Shivam Dube",
    position: "All Rounder",
    team: "Csk",
    img: "https://assets.iplt20.com/ipl/IPLHeadshot2022/5431.png",
  },
  {
    id: 6,
    name: "Deepak Chakar",
    position: "Bowler",
    team: "Csk",
    img: "https://assets.iplt20.com/ipl/IPLHeadshot2022/140.png",
  },
  {
    id: 7,
    name: "Mukesh Choudhary",
    position: "Bowler",
    team: "Csk",
    img: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20575.png",
  },
  {
    id: 8,
    name: "Simerjeeth Singh",
    position: "Bowler",
    team: "Csk",
    img: "https://assets.iplt20.com/ipl/IPLHeadshot2022/10789.png",
  },
  {
    id: 9,
    name: "Dwine pretrious",
    position: "All Rounder",
    team: "Csk",
    img: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20573.png",
  },
  {
    id: 10,
    name: "Mitchel Santer",
    position: "All Rounder",
    team: "Csk",
    img: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1903.png",
  },
  {
    id: 11,
    name: "Devon Convey",
    position: "Batting",
    team: "Csk",
    img: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20572.png",
  },
  {
    id: 12,
    name: "Ruturaj Gaikward",
    position: "Batting",
    team: "Csk",
    img: "https://assets.iplt20.com/ipl/IPLHeadshot2022/5443.png",
  },
];

export default data;
